/* ============================================================
   GoldenMovies — Mock data (Phase 0/1)
   The demo has no real backend. All data lives here and is consumed
   as if it came from an API. Easy to migrate to /api routes later.
   UI labels go through i18n (lib/i18n.ts); here we store keys
   (navKey) that resolve to the label for the active language.
   ============================================================ */

import {
  Home,
  Clapperboard,
  Ticket,
  Popcorn,
  CalendarClock,
  Clock,
  User,
  Shield,
  type LucideIcon,
} from "lucide-react";
import type { DICT } from "./i18n";
import moviesData from "./movies-data.json";

type NavKey = keyof (typeof DICT)["en"]["nav"];

export type NavItem = {
  navKey: NavKey;
  href: string;
  icon: LucideIcon;
  section: "discover" | "account";
};

export const NAV_ITEMS: NavItem[] = [
  { navKey: "home", href: "/", icon: Home, section: "discover" },
  { navKey: "nowShowing", href: "/now-showing", icon: Clapperboard, section: "discover" },
  { navKey: "theaters", href: "/theaters", icon: Ticket, section: "discover" },
  { navKey: "concessions", href: "/concessions", icon: Popcorn, section: "discover" },
  { navKey: "comingSoon", href: "/coming-soon", icon: CalendarClock, section: "discover" },
  { navKey: "presale", href: "/presale", icon: Clock, section: "discover" },
  { navKey: "profile", href: "/profile", icon: User, section: "account" },
  { navKey: "club", href: "/club", icon: Shield, section: "account" },
];

export const CITIES = [
  "Caracas",
  "Valencia",
  "Maracaibo",
] as const;
export type City = (typeof CITIES)[number];

export type Format = "IMAX" | "DOLBY" | "DOLBY3D";
export const FORMATS: Format[] = ["IMAX", "DOLBY", "DOLBY3D"];

const FORMAT_LABELS: Record<Format, string> = {
  IMAX: "IMAX",
  DOLBY: "Dolby Digital",
  DOLBY3D: "Dolby 3D",
};

/** Human-readable format label, with a SUB suffix when subtitled. */
export function formatLabel(f: Format, subtitled = false): string {
  const base = FORMAT_LABELS[f];
  return subtitled ? `${base} SUB` : base;
}

export type Movie = {
  id: string;
  slug: string;
  title: string;
  /** Genre key from the closed set defined in i18n. */
  genre: string;
  rating: number;
  durationMin: number;
  format: Format;
  /** Poster URL from OMDb (m.media-amazon.com). Consumed by next/image via remotePatterns. */
  poster: string;
  certificate: string;
  year: number;
  director: string;
  cast: string[];
  synopsis: string;
  /** YouTube video ID (11 chars) for the official trailer. */
  trailerVideoId: string;
  /** Upcoming release — not yet in theaters. */
  upcoming?: boolean;
  /** Active pre-sale — in theaters but tickets sold in advance. */
  presale?: boolean;
  /** Release date (ISO string) — relevant for upcoming and presale movies. */
  releaseDate?: string;
};

export const FEATURED = {
  title: "The Last Concert",
  titleAccent: "Concert",
  durationMin: 138,
  genre: "Musical",
  format: "DOLBY" satisfies Format,
  certificate: "+13",
};

/* Catalog generated by scripts/seed-movies.ts (OMDb).
   To refresh: npm run seed:movies */
export const MOVIES: Movie[] = moviesData as Movie[];

/* ── Fixed theater model (showtimes, prices, rooms) ── */

export const SHOWTIMES = ["14:00", "16:30", "18:45", "20:30", "22:00"] as const;

/** Base adult ticket price (USD) by theater format. */
export const TICKET_PRICES_USD: Record<Format, number> = {
  IMAX: 10,
  DOLBY: 7,
  DOLBY3D: 8.5,
};

/** Discount multipliers applied on top of the base price. */
export const TICKET_DISCOUNTS = {
  /** Children: 50% off. */
  child: 0.5,
  /** Seniors: 50% off. */
  senior: 0.5,
  /** Popular Monday: 50% off. */
  promo: 0.5,
} as const;

/** Promotional weekdays (0 = Sunday … 6 = Saturday). Monday is the popular day. */
export const PROMO_WEEKDAYS = [1] as const;

export type AudienceType = keyof typeof TICKET_DISCOUNTS | "adult";

/** Computes the final ticket price given format, audience type, and purchase date. */
export function computeTicketPrice(
  format: Format,
  audience: AudienceType,
  date: Date = new Date()
): number {
  const base = TICKET_PRICES_USD[format];
  const isPromoDay = (PROMO_WEEKDAYS as readonly number[]).includes(date.getDay());
  let multiplier = 1;
  if (audience !== "adult") multiplier = TICKET_DISCOUNTS[audience];
  if (isPromoDay) multiplier = Math.min(multiplier, TICKET_DISCOUNTS.promo);
  return Math.round(base * multiplier * 100) / 100;
}

export const RECOMMENDED = MOVIES.filter((m) => !m.upcoming);

export function getMovieBySlug(slug: string): Movie | undefined {
  return MOVIES.find((m) => m.slug === slug);
}

export type Venue = {
  id: string;
  name: string;
  city: City;
  technologies: Format[];
  photo: string;
  address?: string;
};

const venuePhoto = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&h=600&q=80`;

export const VENUES: Venue[] = [
  {
    id: "v2",
    name: "Sambil Caracas",
    city: "Caracas",
    technologies: ["DOLBY", "DOLBY3D"],
    photo: venuePhoto("photo-1626814026160-2237a95fc5a0"),
    address: "Av. Libertador, Chacao",
  },
  {
    id: "v3",
    name: "Millennium",
    city: "Caracas",
    technologies: ["DOLBY", "DOLBY3D"],
    photo: venuePhoto("photo-1594909122845-11baa439b7bf"),
    address: "Av. Río de Janeiro, Las Mercedes",
  },
  {
    id: "v10",
    name: "Tolón",
    city: "Caracas",
    technologies: ["IMAX", "DOLBY", "DOLBY3D"],
    photo: venuePhoto("photo-1485846234645-a62644f84728"),
    address: "Av. Río de Janeiro, Las Mercedes",
  },
  {
    id: "v5",
    name: "Valencia Sur",
    city: "Valencia",
    technologies: ["IMAX", "DOLBY", "DOLBY3D"],
    photo: venuePhoto("photo-1542204165-65bf26472b9b"),
    address: "Av. Bolívar Norte",
  },
  {
    id: "v6",
    name: "Sambil Maracaibo",
    city: "Maracaibo",
    technologies: ["DOLBY", "DOLBY3D"],
    photo: venuePhoto("photo-1505739998589-00fc191ce01d"),
    address: "Av. La Limpia",
  },
];

export type ShowtimeEntry = {
  format: Format;
  subtitled: boolean;
  time: string;
};

export type ShowtimeGroup = {
  venue: string;
  city: City;
  entries: ShowtimeEntry[];
};

/**
 * Canonical 5-showtime template per venue (when IMAX is supported):
 * IMAX → Dolby Digital → Dolby 3D → Dolby Digital SUB → Dolby 3D SUB.
 * If the venue has no IMAX, that slot is replaced with another Dolby Digital
 * so every venue always offers exactly 5 showtimes.
 */
const SHOWTIME_TIMES = ["14:00", "16:30", "18:45", "20:30", "22:00"] as const;

function buildEntries(supportsImax: boolean): ShowtimeEntry[] {
  const slots: Array<{ format: Format; subtitled: boolean }> = supportsImax
    ? [
        { format: "IMAX",    subtitled: false },
        { format: "DOLBY",   subtitled: false },
        { format: "DOLBY3D", subtitled: false },
        { format: "DOLBY",   subtitled: true  },
        { format: "DOLBY3D", subtitled: true  },
      ]
    : [
        { format: "DOLBY",   subtitled: false },
        { format: "DOLBY3D", subtitled: false },
        { format: "DOLBY",   subtitled: true  },
        { format: "DOLBY3D", subtitled: true  },
        { format: "DOLBY",   subtitled: false },
      ];
  return slots.map((s, i) => ({ ...s, time: SHOWTIME_TIMES[i] }));
}

/**
 * Showtimes for a movie. Each venue offers exactly 5 showtimes
 * mixing IMAX, Dolby Digital, and Dolby 3D (with subtitled variants).
 * Optionally filtered by city.
 */
export function getShowtimes(_movie: Movie, city?: City): ShowtimeGroup[] {
  const venues = city ? VENUES.filter((v) => v.city === city) : VENUES;
  return venues.map((v) => ({
    venue: v.name,
    city: v.city,
    entries: buildEntries(v.technologies.includes("IMAX")),
  }));
}

/* ── Concessions (snacks & drinks) ── */
export type ConcessionCategory = "combo" | "popcorn" | "drink" | "candy";

export type Concession = {
  id: string;
  name: string;
  description: string;
  category: ConcessionCategory;
  priceUSD: number;
  image: string;
};

const snackImage = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=600&h=400&q=80`;

export const CONCESSIONS: Concession[] = [
  {
    id: "c1",
    name: "GoldenMovies Combo",
    description: "Large popcorn + 2 large drinks + nachos",
    category: "combo",
    priceUSD: 12.5,
    image: snackImage("photo-1578849278619-e73505e9610f"),
  },
  {
    id: "c2",
    name: "Duo Combo",
    description: "Medium popcorn + 2 medium drinks",
    category: "combo",
    priceUSD: 9.0,
    image: snackImage("photo-1585647347483-22b66260dfff"),
  },
  {
    id: "c3",
    name: "Solo Combo",
    description: "Medium popcorn + drink + candy",
    category: "combo",
    priceUSD: 7.5,
    image: snackImage("photo-1505686994434-e3cc5abf1330"),
  },
  {
    id: "c4",
    name: "Butter Popcorn — Large",
    description: "Classic buttered popcorn, jumbo size",
    category: "popcorn",
    priceUSD: 5.5,
    image: snackImage("photo-1578849278619-e73505e9610f"),
  },
  {
    id: "c5",
    name: "Sweet Popcorn",
    description: "Caramel-glazed, made fresh in-house",
    category: "popcorn",
    priceUSD: 5.0,
    image: snackImage("photo-1505686994434-e3cc5abf1330"),
  },
  {
    id: "c6",
    name: "Cola — Large",
    description: "32 oz fountain drink",
    category: "drink",
    priceUSD: 4.0,
    image: snackImage("photo-1554866585-cd94860890b7"),
  },
  {
    id: "c7",
    name: "Iced Latte",
    description: "Premium espresso with cold milk",
    category: "drink",
    priceUSD: 4.5,
    image: snackImage("photo-1517701604599-bb29b565090c"),
  },
  {
    id: "c8",
    name: "Gummy Mix",
    description: "Assorted fruit-flavored gummies",
    category: "candy",
    priceUSD: 3.5,
    image: snackImage("photo-1581798459219-318e76aecc7b"),
  },
  {
    id: "c9",
    name: "Chocolate Bites",
    description: "Belgian dark chocolate, 120g",
    category: "candy",
    priceUSD: 4.0,
    image: snackImage("photo-1606312619070-d48b4c652a52"),
  },
];

/* ── Promotions ── */
export type Promotion = {
  id: string;
  title: string;
  description: string;
  image: string;
  expiresAt: string;
  cta: string;
};

export const PROMOTIONS: Promotion[] = [
  {
    id: "p1",
    title: "2x1 Tuesdays",
    description:
      "Two tickets for the price of one, every Tuesday. Standard formats only.",
    image: snackImage("photo-1517604931442-7e0c8ed2963c"),
    expiresAt: "2026-12-31",
    cta: "/now-showing",
  },
  {
    id: "p2",
    title: "GoldenMovies Club — 25% off concessions",
    description:
      "Gold members and above enjoy 25% off all combos and popcorn.",
    image: snackImage("photo-1485846234645-a62644f84728"),
    expiresAt: "2026-12-31",
    cta: "/club",
  },
  {
    id: "p3",
    title: "Friday IMAX night",
    description:
      "All IMAX tickets at standard price on Fridays — premium experience, no premium fee.",
    image: snackImage("photo-1574267432553-4b4628081c31"),
    expiresAt: "2026-09-30",
    cta: "/now-showing?format=IMAX",
  },
];

/* ── GoldenMovies Club tiers ── */
export type ClubTier = {
  id: string;
  name: string;
  pointsRequired: number;
  /** Monthly membership price (USD). 0 = free tier. */
  monthlyPriceUSD: number;
  accent: string;
  benefits: { en: string; es: string }[];
};

export const CLUB_TIERS: ClubTier[] = [
  {
    id: "silver",
    name: "Silver",
    pointsRequired: 0,
    monthlyPriceUSD: 0,
    accent: "#c0c0c0",
    benefits: [
      { en: "Earn 1 point per US$ spent", es: "1 punto por US$ gastado" },
      { en: "Birthday free popcorn", es: "Cotufas gratis en tu cumpleaños" },
      { en: "Member-only previews", es: "Pre-estrenos exclusivos" },
    ],
  },
  {
    id: "gold",
    name: "Gold",
    pointsRequired: 2000,
    monthlyPriceUSD: 9.99,
    accent: "#d4af37",
    benefits: [
      { en: "25% off all concessions", es: "25% de descuento en caramelería" },
      { en: "Free upgrade to VIP seats", es: "Upgrade gratis a butacas VIP" },
      { en: "Priority seat selection", es: "Selección prioritaria de asientos" },
      { en: "All Silver benefits", es: "Todos los beneficios Silver" },
    ],
  },
  {
    id: "platinum",
    name: "Platinum",
    pointsRequired: 6000,
    monthlyPriceUSD: 19.99,
    accent: "#e5e4e2",
    benefits: [
      { en: "4 free tickets per month", es: "4 boletos gratis al mes" },
      { en: "Companion ticket on every visit", es: "Boleto de acompañante en cada visita" },
      { en: "Concierge booking line", es: "Línea de reservas concierge" },
      { en: "All Gold benefits", es: "Todos los beneficios Gold" },
    ],
  },
];

export const USER = {
  initials: "CM",
  firstName: "Carlos",
  lastName: "Mendoza",
  city: "Caracas" as const satisfies City,
};
